name: Beta Release

on:
  push:
    branches:
      - "master"

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Visual Studio Shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x86

      - name: Build with nmake
        run: nmake

      - name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          tag_name: beta
          files: |
            bin/*
            LICENSE
